# Generated by Django 3.2.11 on 2022-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
    ]
