# Generated by Django 3.2.11 on 2022-01-30 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220126_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('\\d-\\d{3}-\\d{3}-\\d{4}$', message='Phone must be in *-***-***-**** format.')], verbose_name='Phone number'),
        ),
    ]
