# Generated by Django 3.2.11 on 2022-02-15 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 23, 42, 48, 939793, tzinfo=utc)),
        ),
    ]
