# Generated by Django 3.2.11 on 2022-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_actie',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
