# Generated by Django 3.2.11 on 2022-02-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_productcategory_is_actie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='is_actie',
            new_name='is_active',
        ),
    ]
