# Generated by Django 3.2.11 on 2022-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In process'), ('PAIMENT_AWAITING', 'Payment awaiting'), ('PAID', 'Paid'), ('READY', 'Ready'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='CREATED', max_length=20, verbose_name='Status'),
        ),
    ]
